"
!ActivePapers Pharo edition

*ActivePapers>https://www.activepapers.org/* is a research and development project to improve scientific communication involving computational results. This Pharo edition of ActivePapers explores the user interface and documentation aspects.

An ActivePaper is a package of code, data, and narratives which together convey the results of a computer-aided research study as clearly and precisely as possible.
The main functionality provided by this package ist the ${class:name=APActivePaper}$ class for computational documents.

For a small but complete use case, see ${activePaper:name=InfluenzaLikeIllnessIncidenceInFrance}$. 

"
Class {
	#name : #APDocumentation,
	#superclass : #Object,
	#traits : 'TWkClassWiki',
	#classTraits : 'TWkClassWiki classTrait',
	#category : #'ActivePapers-Documentation'
}
